openai:
  api_key: ${OPENAI_API_KEY}
  model_name: gpt-4-turbo
  temperature: 0.3
  max_tokens: 1024
anthropic:
  api_key: ${ANTHROPIC_API_KEY}
  model_name: claude-3-opus
local_models:
  codegen2_path: /models/codegen2-3.7B